# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 19, 13, 17, 56, 592196, tzinfo=utc)),
        ),
    ]
